### ISSUE TITLE
Include Home Component

### ISSUE THREAD

**Issue by hellotusharkhanna** [SQUATSFITNESS/squats-videos#18]
# This is a Feature Proposal

## Description
Make a default Home Component which will be default route as well. 
SearchVideo Component should have search template only. 
Home Component will have both SearchVideo Component & Video List Component

For feature proposals:
* Segregate app into smaller components in their own respective folders.

**Comment by chimuu** [comment]
I believe keeping it single component ie single page is good enough.

Keep it simple for user, just one page, though we can include multiple features on same page.

**Comment by souvikbasu** [comment]
yes makes sense to refactor the code into multiple components for better maintainability. Although visually we will keep it a single page app for better UX
